spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestTaskXml
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /myapp



